#!/usr/bin/env ruby
# -*- encoding: utf-8 -*-

require 'nkf'

def main

  if $stdin.tty?
    str = ARGV.shift
  else
    str = $stdin.read
  end

  # str = NKF.nkf("-Zw", "aＡあ0０ffい う　えお１（、）a")
  str = NKF.nkf("-Zw", str)
  str.tr!('　',' ')

  # str.tr!(' ','_')

  return str

end

def help_message
  banner = <<-BANNER
Usage: zen2han string
       something | zen2han
  BANNER
  puts banner
end

puts main rescue help_message
