#!/usr/bin/env ruby
# -*- encoding: utf-8 -*-
require 'nkf'

def main

  str = $stdin.tty? ? str = ARGV.shift : $stdin.read

  # str = NKF.nkf("-Zw", "aＡあ0０ffい う　えお１（、）a")
  str = NKF.nkf("-Zw", str)
  str.tr!('　',' ')

  # str.tr!(' ','_')

  return str

end

def help_message
  banner = <<-BANNER
Usage: zen2han string
       something | zen2han
  BANNER
  puts banner
end

puts main rescue help_message
